#!python

Import('*')

ed = env.Command('erase.dummy', [], 'st-flash erase')
env.AlwaysBuild(ed)
env.Alias('erase', ed)

fd = env.Command('flash.dummy', bins[1], 'st-flash --reset --format ihex write $SOURCE')
env.AlwaysBuild(fd)
env.Alias('flash', fd)
